"""
Django settings for PettApp project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8ctx4pa10@+zug-nmq+#26yaz+of)kixp-elgx--*yih!k*wod'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps
    'account',
    'petdata',
    'location',
    # Libraries #
    'rest_framework',
    'django_extensions',
    'django.contrib.gis',
    'leaflet',
   

]
AUTH_USER_MODEL = 'account.User' 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PettApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PettApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "petapp",
        "USER": "postgres",
        "PASSWORD": "3134",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Firebase Credentials #
serviceAccountKey  = {
  "type": "service_account",
  "project_id": "petapp-7f76a",
  "private_key_id": "bf3ebd550fff27c753e617f4d05c63cf658d7659",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDBqBiWQ2IvAP2c\nJ9xw14usnEvR08xzDvC/lLzTGiRz5ufqxzgEJqST7S5vth2KkjPepORa5jEHZpc+\nnkspb43K8QXZDJKuc6DVaEZiZ9n0JhGADy0DIQd83sremz0laeXDY/EoY8EwJK+P\nB0Vmz5mFuRpr/QhDGFlDBHn9Pt0HM8zTkauOQf78yFTmvveRz/ThmfGMp9xUqdER\nNTrfFAyncGH+mfJ7BOc56tmhShmfBbuIAf5bK8U5U0c1VJ5gX4zZ73NJUZCwSmxL\nkbXi/NqCcvCzHEXBJ/Q60fOYY+pS2R1A29ikPezm5eZZPi9/pQ8/PBzv7xHgjjyW\nKuQEOfzBAgMBAAECggEAI6W9duWK/IOGa5kD0UrAFYNEyqhd5V0d8Gog8wwII0Sh\nMry+wTbayzcY+evQVspwXV7FgT0Hz+iw1RA+3i8Abxe8X5aapp22wKnb8O/UdUaP\nqJ7ChqWtEu2Q8vapBArRBk1OnkR0kpfiMCYivpje1fh7ll7Cx1UDU1yO1xDcD1/F\nyfRJM91G/7zjPj98UD9MXrB40aUNOWTym11f82kTMMAXV3pdM6PoZwa3Eobmatgx\ngprvgDamER9G0jpciolRRzXOEvi8bnbCDyB0r6z0drTTbTL9zaKg6jk8EsvOi9N3\nyhNzej1NwsNJJfxidLOdjJ8s7/xnKCZgm9expdYkVQKBgQDsPNgJN13q+ozgOgnY\np+nkKakuYxvuQCw4D4RWBnYDlD9nM/3E9I6dUb8VYRg9qUpBADysLGfcCRLBYPcP\noChhRCUw/uGKT6nDL7UDpYCb8tkloCnlvHYW2TEJfp/SGDyqd8kPWtDwTmAxuRod\np8IYf6vu1r8IOVSsHxfu4JTJ9QKBgQDR21s0VtlSfLWXYMfYvM1zxW9RB7aN6ixP\n6TKPnkE8UjSJlrSWnAvgiZU8dzL600tUssPOivcx9Bbz7AMOgZ4kT6jXUTHw2EwQ\nbdeeLbndtOqVItJPibDnSgnoXX5721n/ufbqzPtvbf1rDEfGS9AtpXDxLQmgGdC7\n//TXJ2UsHQKBgCkFV64iAxjucM/uxA7u+Vo5MbtwUkVIt2T0rNITRSLR90CAcqxk\nmu8OZtPbjE4Iu3AWDnMHMvGuUadqovv/n4NkReEAIUHXG29dNV1wu6hYvwQdj6jo\n1Mia5jzz0+SzeLVRH4SfDHDt6x43OiW0H6wJX12VxI41BlLtA0bjkHKRAoGAJg3M\n4BTPm7GZjDW0h4zVBKVMpjjr1ZgdKPB0hq5/zdxqQnjdjmIFlVXdhfVnfSxLgLRZ\n5V41rQ1CDEFD3KGMd7EqQMEseSv/vwrsCnboOVfRIfIKiPnC5m36lfQ+N19zVnf2\nWmWJQo+DYKH9cevVeDGD5XfxQuLrguvLDijKo9ECgYEAu+WBLeJbJd33JnLreZfN\n/wmZOyUnYhFBIGRucCrpDGiMBFf0ExCevcN3z7ppQL7Bnqmj5E8zuajJAgmuDZqO\ngJcgLA0Iyvk365YhaWgi3OppCCSb1YX9kZr2vPI6csEagTs1FL0a76iZI9GsR+1P\njtQ7m32azs9Y9BvPdzpUQ3M=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-bvw51@petapp-7f76a.iam.gserviceaccount.com",
  "client_id": "114896707277965395715",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-bvw51%40petapp-7f76a.iam.gserviceaccount.com"
}



# Firebase Initializing #
import firebase_admin
from firebase_admin import credentials
from firebase_admin import auth
cred = credentials.Certificate(serviceAccountKey)
firebase_admin.initialize_app(cred)
