# Generated by Django 3.1.5 on 2021-01-18 17:37

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='createPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_image', models.CharField(max_length=255)),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_category', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('transportation', models.BooleanField(default=False)),
                ('saled', models.BooleanField(blank=True, null=True)),
                ('photo1', models.FileField(blank=True, upload_to='media/dp')),
                ('photo2', models.FileField(blank=True, upload_to='media/dp')),
                ('photo3', models.FileField(blank=True, upload_to='media/dp')),
                ('photo4', models.FileField(blank=True, upload_to='media/dp')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
