# Generated by Django 3.1.5 on 2021-01-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpet',
            name='owner_phone',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
