# Generated by Django 3.1.5 on 2021-01-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petdata', '0003_auto_20210121_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpet',
            name='age',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
